language: node_js
sudo: true
dist: trusty
node_js:
  - '8.11'

cache:
  yarn: true
  directories:
     - ./node_modules
     - ./.chrome/chromium
     - ./aio/node_modules

matrix:
  fast_finish: true

before_install:
  - npm install -g @angular/cli
  
install:
  - npm install 
  - npm test sqlite-websql-orm